version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: monorepo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monorepo
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - monorepo-network

  redis:
    image: redis:7-alpine
    container_name: monorepo-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - monorepo-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  monorepo-network:
    driver: bridge
